Rscripts/differential_exon_usage_with_dexseq/dexseq.Rmd
This isn't an actual template, just an example of how to load DEXseq, run it and make some of the plots. It would have to be modified to fit an actual experiment.
=> Add DEXSeq example.

.github/ISSUE_TEMPLATE/feature-request-docs-addition-or-update.md
Some with reminders to people when opening an issue
=> Add issue templates

faq/contributing_to_knowledegebase.md
Added contribution instruction for the pull request method of contribution and some formatting changes to the contribution doc in faq.
=> Rsk patch contrib

README.md, faq/contributing_to_knowledegebase.md
added new tags (after merging with master) and updated links in readme
=> Mm patch newtags

computing/bcbio/multiple_files_bcbio.md, research/scrnaseq/Single-Cell.md, research/scrnaseq/seurat_clustering_analysis.md, research/scrnaseq/seurat_markers.md
added sc headers
added doc for configuring bcbio with multiple files
=> Kr patch sc headers

faq/FAQ_contributions.md, faq/contributing_to_knowledegebase.md
note for now we do not have any subcategory
=> adding headers to the FAQ category

computing/bcbio/bcbio_genomes.md, computing/bcbio/bcbio_tips.md
added headers to the pages in bcbio subfolder
=> headers to bcbio pages

computing/tips_tricks/R-tips-and-tricks.md, computing/tips_tricks/Remove-all-files-except-a-few.md, computing/tips_tricks/Turn-filenames-to-lowercase-and-no-whitespaces.md, computing/tips_tricks/connection-to-hpc.md, computing/tips_tricks/file-transfer.md, computing/tips_tricks/manage-files.md, computing/tips_tricks/scheduler.md
Merge similar information into same files, add headers.
=> organize tips and tricks

faq/contributing_to_knowledegebase.md
First draft of the contribution FAQ.
=> Rsk patch contrib2

research/rnaseq/bibliography.md
Paper comparing normalization methods for RNASeq
=> Add paper to bibliography about normalization

.github/ISSUE_TEMPLATE/feature-request-docs-addition-or-update.md
Just add link to how to contribute as the template for issues
=> Update template for issue 

computing/tips_tricks/OSX.md
=> Add .DS_Store cleanup tip.

computing/tips_tricks/ipython-notebook-on-O2.md
This is some bare bones instructions for getting an IPython notebook running O2 that you can edit on a browser in your local machine but is using the compute and filesystem on O2.
=> Add instructions about how to set up an IPython notebook on O2.

admin/guides/migrate_to_code.md, admin/guides/setting_up_an_analysis_guidelines.md, faq/FAQ_contributions.md, faq/contributing_to_knowledgebase.md
Adding docs to guide people on migrating old repos to GitHub Enterprise
=> addressing issue #70

computing/bcbio/bcbio_genomes.md
This shows the steps you need to take to update, test and install updated versions of transcriptomes for bcbio-supported genomes. This seemed like the right place to put it.
=> Instructions for updating transcriptomes

admin/general_resources/Count-normalization-methods.md, admin/guides/Rshiny-server.md, admin/guides/Sequencing_downloads.md, admin/guides/setting_up_an_analysis_guidelines.md, admin/internal_resources/methods_for_manuscripts.md, computing/tips_tricks/OSX.md, faq/FAQ_contributions.md, faq/contributing_to_knowledgebase.md, research/general_ngs/GeneralNGS.md, research/orphans/3'-DGE.md, research/orphans/improvements.md, research/orphans/single_cell_README.md, research/rnaseq/IRFinder_report.md, research/rnaseq/running_IRFinder.md
Fixing wrong headers so it can compile without error in hugo
=> fix wrong headers

research/rnaseq/bibliography.md
I added a couple of lines explaining my experience with two ways to analyze this and pointed to consults.
=> Update tools used for isoform switching analysis

research/scrnaseq/Single-Cell.md
This was brought up in biogrids-- I spot checked a few of the hits on stuff that is in `tiny-cell-atlas` and there is some overlap.  I'm planning on using this when I get stuck on this step for projects.
=> Add link to biolitmine

research/scrnaseq/tools.md
Updated the single-cell tools document to resemble template
=> Updated to template document format

research/rnaseq/RepEnrich2_guide.md
RepEnrich2 is a way to look at enrichment of repetitive elements. It makes me realize we should release more tools, the code base is a little bit of a mess so I included a link to a fork I made that  had some quality of life improvements that make it a lot more pleasant to run. I wasn't sure what tag to put for this, so I left it blank.
=> Add guide for running RepEnrich2.

research/wgs/crispr-offtarget.md
=> Add HOWTO for doing a CRISPR offtarget analysis

bcbio/bcbio_genomes.md
Location of inputs and results on O2
=> Add info on the whole genome trio (50x) workflow

bcbio/bcbio_genomes.md
Added information about new genome: Human + Covid
=> add Human_covid genome

bcbio/gtf_gff_validator.md
Having context might make this doc more useful (i.e ppl know when they might need to use these tools)
=> Adding a use case 
